reverted test-deb-workflow

diff --git a/.github/workflows/test-deb-workflow.yaml b/.github/workflows/test-deb-workflow.yaml
--- a/.github/workflows/test-deb-workflow.yaml
+++ b/.github/workflows/test-deb-workflow.yaml
@@ -1,13 +1,10 @@
-name: Host Agent - RPM
+name: Host Agent DEB + APT Package
 
 on:
   workflow_dispatch:
     inputs:
       release_version:
-        description: 'Release version for RPM package'
-        required: true
-      release_number:
-        description: 'Release number for RPM package'
+        description: 'Release version for DEB + APT package'
         required: true
   push:
     paths-ignore:
@@ -22,11 +19,10 @@ jobs:
   build:
     runs-on: ubuntu-22.04
     strategy:
-      fail-fast: false
       matrix:
         arch:
-          - x86_64
-          - aarch64
+          - arm64
+          - amd64
       max-parallel: 1
 
     steps:
@@ -34,49 +30,37 @@ jobs:
       if: ${{ github.actor == 'nektos/act' }}
       run: |
         sudo apt-get update
-        sudo apt-get install -y rpm
-      
+        sudo apt-get install -y gettext-base
+  
     - name: Checkout Repo
       uses: actions/checkout@v4
       with:
         token: ${{ secrets.GHCR_TOKEN }}
         ssh-key: ${{ secrets.CHECK_AGENT_ACCESS }}
         submodules: 'recursive'
-        
+
     - name: Set Architecture Variables
       run: |
+        echo "::set-env name=PACKAGE_NAME::mw-agent"
+        echo "::set-env name=BINARY_SOURCE::release/mw-agent"
         if [ -n "${{ github.event.inputs.release_version }}" ]; then
           echo "RELEASE_VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV
         else
           echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
         fi
-        echo "::set-env name=RELEASE_NUMBER::$(echo "${{ github.event.inputs.release_number || 1 }}" | tr -d '\n')"
-        echo "::set-env name=PACKAGE_NAME::mw-agent"
-        echo "::set-env name=SPEC_FILE::mw-agent.spec"
-
+    
+    # Reference : https://www.debian.org/doc/debian-policy/ch-controlfields.html
     - name: Creating Required Folder Structure
       run: |
-        mkdir -p ~/build/rpmbuild/BUILD
-        mkdir -p ~/build/rpmbuild/BUILDROOT
-        mkdir -p ~/build/rpmbuild/RPMS
-        mkdir -p ~/build/rpmbuild/SOURCES
-        mkdir -p ~/build/rpmbuild/SPECS
-        mkdir -p ~/build/rpmbuild/SRPMS
-        mkdir -p ~/build/rpmbuild/SOURCES/${{ matrix.arch }}/${PACKAGE_NAME}-${RELEASE_VERSION}/bin
-        echo '%_topdir %(echo $HOME)/build/rpmbuild' > ~/.rpmmacros
-        cp package-tooling/linux/rpm/$SPEC_FILE ~/build/rpmbuild/SPECS/$SPEC_FILE
-        cp package-tooling/agent-config.yaml.sample \
-        ~/build/rpmbuild/SOURCES/${{ matrix.arch }}/${PACKAGE_NAME}-${RELEASE_VERSION}/agent-config.yaml.sample
-        cp package-tooling/otel-config.yaml.sample \
-        ~/build/rpmbuild/SOURCES/${{ matrix.arch }}/${PACKAGE_NAME}-${RELEASE_VERSION}/otel-config.yaml.sample
-        cp package-tooling/linux/postinst ~/build/rpmbuild/SOURCES/${{ matrix.arch }}/${PACKAGE_NAME}-${RELEASE_VERSION}/postinstall.sh
-        cp package-tooling/linux/mw-agent.service ~/build/rpmbuild/SOURCES/${{ matrix.arch }}/${PACKAGE_NAME}-${RELEASE_VERSION}/mw-agent.service
+        mkdir -p build/apt-repo
+        mkdir -p build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/opt/${PACKAGE_NAME}/bin
+
     - name: Set up Go
+      if: ${{ github.actor != 'nektos/act' }}
       uses: actions/setup-go@v4
       with:
         go-version: 1.22.1
-        cache: false
-    
+
     - name: Set up Git credentials for Go
       run: |
         git config --global url."https://${{ secrets.GHCR_TOKEN }}:@github.com/".insteadOf "https://github.com/"
@@ -86,76 +70,117 @@ jobs:
     # Building with CGO_ENABLED=0 so that we can build static binary which is not dependent on any external libraries
     # Building with -ldflags="-s -w" to reduce the size of binary
     - name: Go Build
-      run: |
-        buildarch="amd64"
-        if [ ${{ matrix.arch }} == "aarch64" ]
-        then
-            buildarch="arm64"
-        fi
-        
-        if [ ${{ github.actor }} != "nektos/act" ]
-        then
-          CGO_ENABLED=0 GOPRIVATE=github.com/middleware-labs GOOS=linux GOARCH=${buildarch} go build \
-          -ldflags="-s -w -X main.agentVersion=${RELEASE_VERSION}" \
-          -v -a -o ~/build/rpmbuild/SOURCES/${{ matrix.arch }}/${PACKAGE_NAME}-${RELEASE_VERSION}/${PACKAGE_NAME} cmd/host-agent/main.go
-        else
-          cp ~/build/mw-host-agent-${buildarch} ~/build/rpmbuild/SOURCES/${{ matrix.arch }}/${PACKAGE_NAME}-${RELEASE_VERSION}/${PACKAGE_NAME}
-        fi
-        
-    - name: Tar Building
-      run: |
-        cd ~/build/rpmbuild/SOURCES/${{ matrix.arch }}
-        tar czvf ~/build/rpmbuild/SOURCES/${PACKAGE_NAME}-${RELEASE_VERSION}-${{ matrix.arch }}.tar.gz \
-        ${PACKAGE_NAME}-${RELEASE_VERSION}/
-
-    - name: Create RPM package
-      run: |
-        rpmbuild -bb --define="release_version ${RELEASE_VERSION}" \
-        --define="release_number ${RELEASE_NUMBER}" \
-        --define="arch ${{ matrix.arch }}" \
-        --define="package_name ${PACKAGE_NAME}" \
-        --target=${{ matrix.arch }} ~/build/rpmbuild/SPECS/$SPEC_FILE
-
-    - name: Acquire lock
       if: ${{ github.actor != 'nektos/act' }}
-      run: flock upload.lock -c "echo Lock acquired"
+      run: |
+        CGO_ENABLED=0 GOPRIVATE=github.com/middleware-labs GOOS=linux GOARCH=${{ matrix.arch }} go build -ldflags="-s -w -X main.agentVersion=${RELEASE_VERSION}" -v -a -o $BINARY_SOURCE cmd/host-agent/main.go
+        
+    - name: Copying code binary into target location
+      run: |
+          if [ ${{ github.actor }} == "nektos/act" ]
+          then
+              cp build/mw-host-agent-${{ matrix.arch }} build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/opt/${PACKAGE_NAME}/bin/${PACKAGE_NAME}
+          else 
+            cp $BINARY_SOURCE build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/opt/${PACKAGE_NAME}/bin/${PACKAGE_NAME}
+          fi
 
-    # - name: Upload artifacts to Github Pages (yum.middleware.io)
+    - name: Copy Linux root files & generate dpkg Control file
+      run: |
+          mkdir -p build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/DEBIAN
+          mkdir -p build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/etc/${PACKAGE_NAME}
+          mkdir -p build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/lib/systemd/system
+
+          cp package-tooling/agent-config.yaml.sample build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/etc/${PACKAGE_NAME}/agent-config.yaml.sample
+          cp package-tooling/otel-config.yaml.sample build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/etc/${PACKAGE_NAME}/otel-config.yaml.sample
+
+          cp package-tooling/linux/postinst build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/DEBIAN/postinst
+          cp package-tooling/linux/prerm build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/DEBIAN/prerm
+          cp package-tooling/linux/postrm build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/DEBIAN/postrm
+          chmod 0755 build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/DEBIAN/postinst
+          chmod 0755 build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/DEBIAN/prerm
+          chmod 0755 build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/DEBIAN/postrm
+
+          cp package-tooling/linux/mw-agent.service build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/lib/systemd/system/mw-agent.service
+
+          PACKAGE=${PACKAGE_NAME} VERSION=${RELEASE_VERSION} ARCHITECTURE=${{ matrix.arch }} envsubst < package-tooling/linux/deb/control > build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}/DEBIAN/control
+
+    - name: Creating DEB package
+      run: |
+          dpkg-deb --build -Z xz build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}
+          dpkg-deb --info build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}.deb
+          dpkg-deb --contents build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}.deb
+
+    # - name: Set up aptly
     #   if: ${{ github.actor != 'nektos/act' }}
     #   run: |
-    #     git clone https://.:${{ secrets.GHCR_TOKEN }}@github.com/middleware-labs/yum.middleware.io.git    
-    #     cp -r ~/build/rpmbuild/RPMS/${{ matrix.arch }}/${PACKAGE_NAME}-${RELEASE_VERSION}-${RELEASE_NUMBER}.${{ matrix.arch }}.rpm \
-    #     yum.middleware.io/${{ matrix.arch }}/Packages/
-       
-    #     cd yum.middleware.io
+    #     # Download aptly binary
+    #     wget https://github.com/aptly-dev/aptly/releases/download/v1.5.0/aptly_1.5.0_linux_amd64.tar.gz
+    #     tar -xzf aptly_1.5.0_linux_amd64.tar.gz
+    #     chmod +x aptly_1.5.0_linux_amd64/aptly
+         
+    #     # Move aptly binary to a directory in PATH
+    #     sudo mv aptly_1.5.0_linux_amd64/aptly /usr/local/bin/
+
+    
+    # - name: Verify aptly version
+    #   if: ${{ github.actor != 'nektos/act' }}
+    #   run: aptly version
+
+    # # Reference : https://www.aptly.info/doc/
+    # - name: Add DEB to MW APT Repo
+    #   if: ${{ github.actor != 'nektos/act' }}
+    #   run: |
+    #     sudo apt-get install -y gnupg
+    #     git clone https://.:${{ secrets.GHCR_TOKEN }}@github.com/middleware-labs/apt.middleware.io.git
+    #     gpg --import apt.middleware.io/gpg-keys/mw-agent-apt-private.key
+    #     gpg --import apt.middleware.io/gpg-keys/mw-agent-apt-public.key
+        
+    #     APTLY_HOME=$(aptly config show | grep rootDir | cut -d '"' -f 4)
+    #     echo "APTLY_HOME=$APTLY_HOME" >> $GITHUB_ENV
+
+    #     cat ~/.aptly.conf
+
+    #     echo $APTLY_HOME
+    #     mkdir -p $APTLY_HOME/public
+    #     mkdir -p $APTLY_HOME/db
+    #     mkdir -p $APTLY_HOME/pool
+    #     chmod 755 $APTLY_HOME
+    #     chmod 755 $APTLY_HOME/*
+    #     ls -l apt.middleware.io
+    #     cp -r apt.middleware.io/db/* $APTLY_HOME/db/
+    #     cp -r apt.middleware.io/public/* $APTLY_HOME/public/
+    #     cp -r apt.middleware.io/pool/* $APTLY_HOME/pool/
+    #     aptly repo list
+    #     aptly repo add --force-replace mw-repo build/${PACKAGE_NAME}_${RELEASE_VERSION}_${{ matrix.arch }}.deb
+    #     aptly repo list
+    #     gpg --list-keys
+    #     gpg --list-secret-keys
+        
+    #     ls -l $APTLY_HOME/pool
+    #     aptly publish update -force-overwrite stable
+    #     ls -l $APTLY_HOME/pool
+    #     echo "sleep 5"
+    #     sleep 5
+    #     ls -l $APTLY_HOME/pool
+    #     cp -r $APTLY_HOME/* apt.middleware.io
+
+    #     cd apt.middleware.io
     #     git config --global user.email "keval@middleware.io"
     #     git config --global user.name "bhogayatakb"
     #     git add .
-    #     git commit -m "RPM added to yum.middleware.io"
-    #     git fetch origin master
-    #     git merge origin/master
+    #     git commit -m "apt.middleware.io updated"
     #     git push origin master
-    
-    - name: Release lock
-      if: ${{ github.actor != 'nektos/act' }}
-      run: flock upload.lock -c "echo Lock released"
-    - name: Delay
-      if: ${{ github.actor != 'nektos/act' }}
-      run: sleep 10
+# distribution = stable, wheezy
+# architectures = all, amd64, arm64
+# component = main, contrib, non-free
 
-    - name: Upload RPM as artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: mw-agent-${{ matrix.arch }}-rpm
-        path: ~/build/rpmbuild/RPMS/${{ matrix.arch }}/mw-agent-${{ env.RELEASE_VERSION }}-${{ env.RELEASE_NUMBER }}.${{ matrix.arch }}.rpm
-        retention-days: 1  
-
+   
   upload-to-release:
     needs: build
     runs-on: ubuntu-latest
-    
+  
     steps:
     - name: Download all artifacts
+      if: ${{ github.actor != 'nektos/act' }}  # Only run on GitHub
       uses: actions/download-artifact@v3
       with:
         path: ./artifacts
@@ -169,35 +194,54 @@ jobs:
         && sudo apt update \
         && sudo apt install gh -y
 
+    - name: Local Release Test
+      if: ${{ github.actor == 'nektos/act' }}
+      run: |
+        VERSION="${{ github.event.inputs.release_version }}"
+        ARTIFACTS_DIR="${GITHUB_WORKSPACE}/local-artifacts"
+        
+        echo "Looking for artifacts in workspace:"
+        ls -R "${ARTIFACTS_DIR}/" || echo "No files in ${ARTIFACTS_DIR}"
+        
+        # For each architecture
+        for arch in arm64 amd64; do
+          echo "Processing $arch architecture"
+          FILE="${ARTIFACTS_DIR}/mw-agent-${arch}-deb/${PACKAGE_NAME}_${VERSION}_${arch}.deb"
+          if [ -f "$FILE" ]; then
+            echo "Found file for upload: $FILE"
+          else
+            echo "Warning: $FILE not found"
+            echo "Current directory contents:"
+            ls -la .
+            echo "Build directory contents:"
+            ls -la build/ || echo "No build directory"
+          fi
+        done
+
     - name: Create and upload to release
+      if: ${{ github.actor != 'nektos/act' }}
       env:
+        # Use GITHUB_TOKEN instead of GHCR_TOKEN for your fork
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         VERSION="${{ github.event.inputs.release_version }}"
-        REL_NUM="${{ github.event.inputs.release_number }}"
         if [ -z "$VERSION" ]; then
           VERSION="${GITHUB_REF#refs/tags/}"
         fi
-        if [ -z "$REL_NUM" ]; then
-          REL_NUM="1"
-        fi
         
         # Debug info
-        echo "VERSION: $VERSION"
-        echo "REL_NUM: $REL_NUM"
         echo "Artifacts directory content:"
         ls -R ./artifacts
         
         # For each architecture
-        for arch in x86_64 aarch64; do
+        for arch in arm64 amd64; do
           echo "Processing $arch architecture"
-          FILE="./artifacts/mw-agent-${arch}-rpm/mw-agent-${VERSION}-${REL_NUM}.${arch}.rpm"
+          FILE="./artifacts/mw-agent-${arch}-deb/mw-agent_${VERSION}_${arch}.deb"
           if [ -f "$FILE" ]; then
             echo "Uploading $FILE to release $VERSION"
+            # Add --repo flag to specify your fork
             gh release upload "$VERSION" "$FILE" --clobber --repo ${{ github.repository }}
           else
             echo "Warning: $FILE not found"
-            echo "Checking actual file path:"
-            find ./artifacts -type f -name "*.rpm"
           fi
         done
